name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://www.dashboard-bot.ga
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: |
          echo "NguyenCongMinh"
      
